// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"border-t py-12 bg-gray-50\"><div class=\"container mx-auto px-4\"><div class=\"grid grid-cols-1 md:grid-cols-4 gap-8\"><div><h3 class=\"font-bold mb-4\">Company</h3><ul class=\"space-y-2\"><li><a href=\"#\" class=\"text-sm text-gray-500 hover:text-gray-900\">About Us</a></li><li><a href=\"#\" class=\"text-sm text-gray-500 hover:text-gray-900\">Contact Us</a></li></ul></div><div><h3 class=\"font-bold mb-4\">Community</h3><ul class=\"space-y-2\"><li><a href=\"/docs\" class=\"text-sm text-gray-500 hover:text-gray-900\">API Documentation</a></li><li><a href=\"#\" class=\"text-sm text-gray-500 hover:text-gray-900\">Network Status</a></li></ul></div><div><h3 class=\"font-bold mb-4\">Products</h3><ul class=\"space-y-2\"><li><a href=\"https://eth-chat.conceptcodes.dev\" class=\"text-sm text-gray-500 hover:text-gray-900\">Eth Chat</a></li><li><a href=\"#\" class=\"text-sm text-gray-500 hover:text-gray-900\">API Services</a></li></ul></div><div><h3 class=\"font-bold mb-4\">Connect</h3><ul class=\"space-y-2\"><li><a href=\"https://github.com/conceptcodes/eth-indexer-go\" class=\"text-sm text-gray-500 hover:text-gray-900\">GitHub</a></li></ul></div></div><div class=\"mt-8 pt-8 border-t text-center text-sm text-gray-500\"><p>© <script>document.write(new Date().getFullYear() + \" \")</script>ConceptCodes, LLC. All rights reserved.</p></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
