// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NotFound() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen gradient-bg flex items-center justify-center p-4\"><div class=\"max-w-2xl mx-auto text-center\"><!-- 404 Icon --><div class=\"mb-8 float-animation\"><div class=\"w-40 h-40 mx-auto bg-white rounded-full flex items-center justify-center\"><i data-lucide=\"ghost\" class=\"w-24 h-24 text-indigo-600\"></i></div></div><!-- Error Message --><h1 class=\"text-5xl font-bold text-white mb-4\">404</h1><h2 class=\"text-2xl font-semibold text-indigo-100 mb-4\">Page Not Found</h2><p class=\"text-indigo-100 mb-8 max-w-md mx-auto\">Oops! The page you're looking for has vanished into the blockchain...</p><!-- Navigation Buttons --><div class=\"flex flex-col sm:flex-row gap-4 justify-center\"><a href=\"/\" class=\"inline-flex items-center justify-center px-6 py-3 bg-white text-indigo-600 rounded-lg font-medium hover:bg-indigo-50 transition-colors\"><i data-lucide=\"home\" class=\"w-5 h-5 mr-2\"></i> Go Home</a> <button onclick=\"history.back()\" class=\"inline-flex items-center justify-center px-6 py-3 bg-indigo-500 text-white rounded-lg font-medium hover:bg-indigo-400 transition-colors\"><i data-lucide=\"arrow-left\" class=\"w-5 h-5 mr-2\"></i> Go Back</button></div><!-- Quick Links --><!-- Help Text --><p class=\"mt-12 text-sm text-indigo-100\">Need help?  <a href=\"/contact\" class=\"underline hover:text-white\">Contact Support</a></p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Page().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
